import Head from 'next/head'
import styles from '@/styles/Home.module.css'
import useSWR from "swr";

type News = {
  title: string,
  url: string,
  id: string
}

export async function getServerSideProps() {
    const res = await fetch("https://hacker-news.firebaseio.com/v0/topstories.json");
    const json = await res.json();
    const urls = json.map((id: string) => `https://hacker-news.firebaseio.com/v0/item/${id}.json`).slice(0, 30);
    const reqs = urls.map((url: string) => fetch(url).then((res) => res.json()));
    const news = await Promise.all(reqs);
    return {
      props: {
        news
      }
    };
}

export default function Home({ news }: { news: News[] }) {
  return (
    <>
      <Head>
        <title>Hacker News App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
        <div className={styles.center}>
          <h1>Hacker News Application</h1>
        </div>
        <div className={styles.center}>
          <div>
            <ul>
              {news?.map((news: News) => <li key={news.id}><a href={news.id}>{news.title}</a></li>)}
            </ul>
          </div>
        </div>
      </main>
    </>
  )
}
